export const config = {
    readonly: false,
    minHeight: "250px",
    allowResizeY: false,
    buttons: [
      "font",
      "fontsize",
      "|",
      "bold",
      "italic",
      "underline",
      "eraser",
      "|",
      "ul",
      "ol",
      "|",
      "brush",
      "table",
      "left",
      "center",
      "right",
      "justify",
    ],
    removeButtons: [
      "source",
      "|",
      "brush",
      "|",
      "|",
      "paragraph",
      "|",
      "image",
      "link",
      "|",
      "|",
      "undo",
      "redo",
      "|",
      "hr",
      "fullsize",
      "copyformat",
      "source",
    ],
    enter: "div",
    showXPathInStatusbar: false,
    showCharsCounter: false,
    showWordsCounter: false,
    toolbarAdaptive: false,
    toolbarSticky: true,
    autofocus: false,
    addNewLine: false,
    saveSelectionOnBlur: false,
    askBeforePasteHTML: false,
    cursorAfterAutofocus: "end",
    askBeforePasteFromWord: false,
    defaultActionOnPaste: "insert_only_text",
    placeholder: "Ingrese texto aca",
    defaultActionOnPasteFromWord: "insert_only_text",
    style:{
        padding: '0px 20px 0px 20px'
    }
  }